### ISSUE TITLE
for loop rendered as an operation not a loop

### ISSUE THREAD

**Issue by psychemedia** [cdfmlr/pyflowchart#9]
One of the things I noticed in your demo is that a `for` loop is rendered as a `while` in an *operation* block whereas a while is rendered (more usefully) in looped decision. Is there any way of rendering the `for` loop as a looped decision without manually converting the code to explicitly use a `while`?

**Comment by cdfmlr** [comment]
Sorry to bewilder you. Well, I guess you are perplexing about the [`simplify`](https://github.com/cdfmlr/pyflowchart#simplify) feature, yes, it's a feature instead of a bug:). It's not about the `for` or `while` (both concerned by pyflowchart as a `Loop`), it's regarding to the length of your loop bodies.

By default, PyFlowchart will simplify the `if`, `for` as well as `while` that has only one line bodies. For example:

```python
if a < 4:
    print(a)
```

This will be simplified as an operation block: `print(a) if a < 4`, instead of a verbose ConditionNode + a OperationNode and a looping arrow. I think it's more natural to read. And in my practice,  if there were lots of such one-line-body sentences (very common for some algorithm codes), the generated flowchart without simplifying will be horrible.

If you dislike this feature, just disable it by pass a `simplify=False` to the `Flowchart.from_code`. Go [this section of readme](https://github.com/cdfmlr/pyflowchart#simplify) for more details.

**Comment by psychemedia** [comment]
Ah, okay, thanks. I thought I'd tried that but that must have been in a different context.

**Comment by psychemedia** [comment]
Just as a postscript to that, I wrote a review of some of the ways I think that `pyflowchart` might support the creation, and use, of teaching and learning materials: https://blog.ouseful.info/2021/06/17/helping-learners-look-at-their-code/

**Comment by cdfmlr** [comment]
@psychemedia 

> Just as a postscript to that, & FYI, I wrote a review of some of the ways I think that `pyflowchart` might support the creation, and use, of teaching and learning materials: https://blog.ouseful.info/2021/06/17/helping-learners-look-at-their-code/

Hi, I'd like to share with you that, thanks for your prompt, my new version of PyFlowchart [v0.1.4](https://github.com/cdfmlr/pyflowchart/releases/tag/v0.1.4) has an improvement on the way the unique identifiers are designed, as mentioned in [your blog](https://blog.ouseful.info/2021/06/17/helping-learners-look-at-their-code/). Instead of using the lengthy python build-in object id, now it's more clearer and readable for humans.
